### ISSUE TITLE
multiprocessing tracking bug

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/chitin#27]
For some stupid reason I thought adding `multiprocessing` to the mix was a great idea.
Now there is a ton of wonky shit going on simultaneously:

* [x] Potential to run sequential commands out-of-order
* [x] stderr and stdout interrupt the console
* [x] Zombie processes (ish)
* [ ] Gross code. Specifically to handle apparently incorrect attributes
* [x] Bash script variable capturing broken (the context to pass back data is lost)
* [x] CPU usage wasted by empty zombies that poll and timeout
* [x] Files edited by multiple processes will not be trackable to particular Events

**Comment by SamStudio8** [comment]
We probably need to make the post command handler static, this will at least avoid the expectation that the Chitin object is the very same. The `ChitinDaemon` therefore shouldn't hold a `Chitin` object either, seeing as it isn't the same one anyway. Fucking `multiprocessing`.

**Comment by SamStudio8** [comment]
Half fixed the zombie problem. Apparently `.terminate()` just isn't good enough to make the process go away. The parent needs to clean up, which won't happen until the `run` daemon is dead? For now we can just make sure a sentinel exists when using Chitin scripts, but we'll need to be more clever for the shell, I suspect.

**Comment by SamStudio8** [comment]
Not an easy solution to prevent stderr and stdout mashing up the prompt, unfortunately.
See jonathanslenders/python-prompt-toolkit#429

**Comment by SamStudio8** [comment]
stderr and stdout interrupt fixed by 54212a7

**Comment by SamStudio8** [comment]
bash script variable capturing removed as a feature

**Comment by SamStudio8** [comment]
Commands are now ordered and cannot be executed out of submitted order, this also means metadata events for files or folders edited by multiple commands are correctly handled as an added bonus. Hooray.

Managed to fix the polling zombie nonsense.

The code is still disgusting, but that can wait a little longer.
